name: CI/CD

on:
  push:
    branches: [master, main]

  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run Linter
        run: |
          jshint ./giftlink-backend/app.js
          jshint ./giftlink-backend/auth.js
          jshint ./giftlink-backend/giftRoutes.js
          jshint ./giftlink-backend/searchRoutes.js

          echo "Linted all JS files successfully"

  client_build:
    name: Build Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./giftlink-frontend
        run: npm install

      - name: Build client
        working-directory: ./giftlink-frontend
        run: npm run build
